CREATE TABLE USUARIO (
  UsuCod BIGINT UNSIGNED PRIMARY KEY,
  UsuCor VARCHAR(80) NOT NULL UNIQUE,
  UsuCon VARCHAR(80) NOT NULL,
  UsuNom VARCHAR(80) NOT NULL,
  UsuEstReg CHAR(1)
);

CREATE TABLE PRODUCTO (
  ProCod BIGINT UNSIGNED PRIMARY KEY,
  ProNom VARCHAR(80) NOT NULL UNIQUE,
  ProDes TEXT NOT NULL,
  ProCat VARCHAR(40) NOT NULL,
  ProPre DECIMAL(10,2) NOT NULL,
  ProFot TEXT,
  ProEti TEXT,
  ProEstReg CHAR(1)
);

CREATE TABLE PLAN_DIETA (
  PlaCod BIGINT UNSIGNED PRIMARY KEY,
  PlaNom VARCHAR(80) NOT NULL UNIQUE,
  PlaIng TEXT NOT NULL,
  PlaFot TEXT,
  PlaDes TEXT NOT NULL,
  PlaEti TEXT,
  PlaEstReg CHAR(1)
);

CREATE TABLE CARRITO (
  CarCod BIGINT UNSIGNED PRIMARY KEY,
  CarUsuCod BIGINT UNSIGNED NOT NULL,
  CarFec DATETIME NOT NULL,
  CarEstReg CHAR(1),
  FOREIGN KEY (CarUsuCod) REFERENCES USUARIO(UsuCod)
);

CREATE TABLE PEDIDO (
  PedCod BIGINT UNSIGNED PRIMARY KEY,
  PedUsuCod BIGINT UNSIGNED NOT NULL,
  PedFec DATETIME NOT NULL,
  PedMon DECIMAL(10,2) NOT NULL,
  PedEst VARCHAR(20) NOT NULL,
  PedEstReg CHAR(1),
  FOREIGN KEY (PedUsuCod) REFERENCES USUARIO(UsuCod)
);

CREATE TABLE PERFIL_MASCOTA (
  PerCod BIGINT UNSIGNED PRIMARY KEY,
  PerUsuCod BIGINT UNSIGNED NOT NULL,
  PerNom VARCHAR(80) NOT NULL,
  PerEsp VARCHAR(20) NOT NULL,
  PerRaz VARCHAR(40) NOT NULL,
  PerEda INT NOT NULL,
  PerPes DECIMAL(10,2) NOT NULL,
  PerFot TEXT,
  PerAle TEXT,
  PerCon TEXT,
  PerEstReg CHAR(1),
  FOREIGN KEY (PerUsuCod) REFERENCES USUARIO(UsuCod)
);

CREATE TABLE RECETA (
  RecCod BIGINT UNSIGNED PRIMARY KEY,
  RecUsuCod BIGINT UNSIGNED NOT NULL,
  RecArc TEXT NOT NULL,
  RecFec DATETIME NOT NULL,
  RecTip VARCHAR(20) NOT NULL,
  RecEstReg CHAR(1),
  FOREIGN KEY (RecUsuCod) REFERENCES USUARIO(UsuCod)
);

CREATE TABLE ITEM_CARRITO (
  IteCod BIGINT UNSIGNED PRIMARY KEY,
  IteCarCod BIGINT UNSIGNED NOT NULL,
  IteProCod BIGINT UNSIGNED NOT NULL,
  IteCan INT NOT NULL,
  IteEstReg CHAR(1),
  FOREIGN KEY (IteCarCod) REFERENCES CARRITO(CarCod),
  FOREIGN KEY (IteProCod) REFERENCES PRODUCTO(ProCod)
);

CREATE TABLE DETALLE_PEDIDO (
  DetCod BIGINT UNSIGNED PRIMARY KEY,
  DetPedCod BIGINT UNSIGNED NOT NULL,
  DetProCod BIGINT UNSIGNED NOT NULL,
  DetCan INT NOT NULL,
  DetSub DECIMAL(10,2) NOT NULL,
  DetEstReg CHAR(1),
  FOREIGN KEY (DetPedCod) REFERENCES PEDIDO(PedCod),
  FOREIGN KEY (DetProCod) REFERENCES PRODUCTO(ProCod)
);

CREATE TABLE PAGO (
  PagCod BIGINT UNSIGNED PRIMARY KEY,
  PagPedCod BIGINT UNSIGNED NOT NULL,
  PagMon DECIMAL(10,2) NOT NULL,
  PagMet VARCHAR(20) NOT NULL,
  PagCon VARCHAR(40) NOT NULL,
  PagFec DATETIME NOT NULL,
  PagEstReg CHAR(1),
  FOREIGN KEY (PagPedCod) REFERENCES PEDIDO(PedCod)
);

